python3 tweet.py 1 1 >> testOutput.txt
python3 tweet.py 1 2 >> testOutput.txt
python3 tweet.py 1 3 >> testOutput.txt
python3 tweet.py 1 4 >> testOutput.txt
python3 tweet.py 1 5 >> testOutput.txt
python3 tweet.py 1 6 >> testOutput.txt
python3 tweet.py 1 7 >> testOutput.txt
python3 tweet.py 1 8 >> testOutput.txt
python3 tweet.py 1 9 >> testOutput.txt
python3 tweet.py 1 10 >> testOutput.txt
python3 tweet.py 1 11 >> testOutput.txt
python3 tweet.py 1 12 >> testOutput.txt
python3 tweet.py 1 13 >> testOutput.txt
python3 tweet.py 1 14 >> testOutput.txt
python3 tweet.py 1 15 >> testOutput.txt
python3 tweet.py 1 16 >> testOutput.txt
python3 tweet.py 1 17 >> testOutput.txt
python3 tweet.py 1 18 >> testOutput.txt
python3 tweet.py 1 19 >> testOutput.txt
python3 tweet.py 1 20 >> testOutput.txt
python3 tweet.py 1 21 >> testOutput.txt
python3 tweet.py 1 22 >> testOutput.txt
python3 tweet.py 1 23 >> testOutput.txt
python3 tweet.py 1 24 >> testOutput.txt
python3 tweet.py 1 25 >> testOutput.txt
python3 tweet.py 1 26 >> testOutput.txt
python3 tweet.py 1 27 >> testOutput.txt
python3 tweet.py 1 28 >> testOutput.txt
python3 tweet.py 1 29 >> testOutput.txt
python3 tweet.py 1 30 >> testOutput.txt
python3 tweet.py 1 31 >> testOutput.txt
python3 tweet.py 2 1 >> testOutput.txt
python3 tweet.py 2 2 >> testOutput.txt
python3 tweet.py 2 3 >> testOutput.txt
python3 tweet.py 2 4 >> testOutput.txt
python3 tweet.py 2 5 >> testOutput.txt
python3 tweet.py 2 6 >> testOutput.txt
python3 tweet.py 2 7 >> testOutput.txt
python3 tweet.py 2 8 >> testOutput.txt
python3 tweet.py 2 9 >> testOutput.txt
python3 tweet.py 2 10 >> testOutput.txt
python3 tweet.py 2 11 >> testOutput.txt
python3 tweet.py 2 12 >> testOutput.txt
python3 tweet.py 2 13 >> testOutput.txt
python3 tweet.py 2 14 >> testOutput.txt
python3 tweet.py 2 15 >> testOutput.txt
python3 tweet.py 2 16 >> testOutput.txt
python3 tweet.py 2 17 >> testOutput.txt
python3 tweet.py 2 18 >> testOutput.txt
python3 tweet.py 2 19 >> testOutput.txt
python3 tweet.py 2 20 >> testOutput.txt
python3 tweet.py 2 21 >> testOutput.txt
python3 tweet.py 2 22 >> testOutput.txt
python3 tweet.py 2 23 >> testOutput.txt
python3 tweet.py 2 24 >> testOutput.txt
python3 tweet.py 2 25 >> testOutput.txt
python3 tweet.py 2 26 >> testOutput.txt
python3 tweet.py 2 27 >> testOutput.txt
python3 tweet.py 2 28 >> testOutput.txt
python3 tweet.py 3 1 >> testOutput.txt
python3 tweet.py 3 2 >> testOutput.txt
python3 tweet.py 3 3 >> testOutput.txt
python3 tweet.py 3 4 >> testOutput.txt
python3 tweet.py 3 5 >> testOutput.txt
python3 tweet.py 3 6 >> testOutput.txt
python3 tweet.py 3 7 >> testOutput.txt
python3 tweet.py 3 8 >> testOutput.txt
python3 tweet.py 3 9 >> testOutput.txt
python3 tweet.py 3 10 >> testOutput.txt
python3 tweet.py 3 11 >> testOutput.txt
python3 tweet.py 3 12 >> testOutput.txt
python3 tweet.py 3 13 >> testOutput.txt
python3 tweet.py 3 14 >> testOutput.txt
python3 tweet.py 3 15 >> testOutput.txt
python3 tweet.py 3 16 >> testOutput.txt
python3 tweet.py 3 17 >> testOutput.txt
python3 tweet.py 3 18 >> testOutput.txt
python3 tweet.py 3 19 >> testOutput.txt
python3 tweet.py 3 20 >> testOutput.txt
python3 tweet.py 3 21 >> testOutput.txt
python3 tweet.py 3 22 >> testOutput.txt
python3 tweet.py 3 23 >> testOutput.txt
python3 tweet.py 3 24 >> testOutput.txt
python3 tweet.py 3 25 >> testOutput.txt
python3 tweet.py 3 26 >> testOutput.txt
python3 tweet.py 3 27 >> testOutput.txt
python3 tweet.py 3 28 >> testOutput.txt
python3 tweet.py 3 29 >> testOutput.txt
python3 tweet.py 3 30 >> testOutput.txt
python3 tweet.py 3 31 >> testOutput.txt
python3 tweet.py 4 1 >> testOutput.txt
python3 tweet.py 4 2 >> testOutput.txt
python3 tweet.py 4 3 >> testOutput.txt
python3 tweet.py 4 4 >> testOutput.txt
python3 tweet.py 4 5 >> testOutput.txt
python3 tweet.py 4 6 >> testOutput.txt
python3 tweet.py 4 7 >> testOutput.txt
python3 tweet.py 4 8 >> testOutput.txt
python3 tweet.py 4 9 >> testOutput.txt
python3 tweet.py 4 10 >> testOutput.txt
python3 tweet.py 4 11 >> testOutput.txt
python3 tweet.py 4 12 >> testOutput.txt
python3 tweet.py 4 13 >> testOutput.txt
python3 tweet.py 4 14 >> testOutput.txt
python3 tweet.py 4 15 >> testOutput.txt
python3 tweet.py 4 16 >> testOutput.txt
python3 tweet.py 4 17 >> testOutput.txt
python3 tweet.py 4 18 >> testOutput.txt
python3 tweet.py 4 19 >> testOutput.txt
python3 tweet.py 4 20 >> testOutput.txt
python3 tweet.py 4 21 >> testOutput.txt
python3 tweet.py 4 22 >> testOutput.txt
python3 tweet.py 4 23 >> testOutput.txt
python3 tweet.py 4 24 >> testOutput.txt
python3 tweet.py 4 25 >> testOutput.txt
python3 tweet.py 4 26 >> testOutput.txt
python3 tweet.py 4 27 >> testOutput.txt
python3 tweet.py 4 28 >> testOutput.txt
python3 tweet.py 4 29 >> testOutput.txt
python3 tweet.py 4 30 >> testOutput.txt
python3 tweet.py 5 1 >> testOutput.txt
python3 tweet.py 5 2 >> testOutput.txt
python3 tweet.py 5 3 >> testOutput.txt
python3 tweet.py 5 4 >> testOutput.txt
python3 tweet.py 5 5 >> testOutput.txt
python3 tweet.py 5 6 >> testOutput.txt
python3 tweet.py 5 7 >> testOutput.txt
python3 tweet.py 5 8 >> testOutput.txt
python3 tweet.py 5 9 >> testOutput.txt
python3 tweet.py 5 10 >> testOutput.txt
python3 tweet.py 5 11 >> testOutput.txt
python3 tweet.py 5 12 >> testOutput.txt
python3 tweet.py 5 13 >> testOutput.txt
python3 tweet.py 5 14 >> testOutput.txt
python3 tweet.py 5 15 >> testOutput.txt
python3 tweet.py 5 16 >> testOutput.txt
python3 tweet.py 5 17 >> testOutput.txt
python3 tweet.py 5 18 >> testOutput.txt
python3 tweet.py 5 19 >> testOutput.txt
python3 tweet.py 5 20 >> testOutput.txt
python3 tweet.py 5 21 >> testOutput.txt
python3 tweet.py 5 22 >> testOutput.txt
python3 tweet.py 5 23 >> testOutput.txt
python3 tweet.py 5 24 >> testOutput.txt
python3 tweet.py 5 25 >> testOutput.txt
python3 tweet.py 5 26 >> testOutput.txt
python3 tweet.py 5 27 >> testOutput.txt
python3 tweet.py 5 28 >> testOutput.txt
python3 tweet.py 5 29 >> testOutput.txt
python3 tweet.py 5 30 >> testOutput.txt
python3 tweet.py 5 31 >> testOutput.txt
python3 tweet.py 6 1 >> testOutput.txt
python3 tweet.py 6 2 >> testOutput.txt
python3 tweet.py 6 3 >> testOutput.txt
python3 tweet.py 6 4 >> testOutput.txt
python3 tweet.py 6 5 >> testOutput.txt
python3 tweet.py 6 6 >> testOutput.txt
python3 tweet.py 6 7 >> testOutput.txt
python3 tweet.py 6 8 >> testOutput.txt
python3 tweet.py 6 9 >> testOutput.txt
python3 tweet.py 6 10 >> testOutput.txt
python3 tweet.py 6 11 >> testOutput.txt
python3 tweet.py 6 12 >> testOutput.txt
python3 tweet.py 6 13 >> testOutput.txt
python3 tweet.py 6 14 >> testOutput.txt
python3 tweet.py 6 15 >> testOutput.txt
python3 tweet.py 6 16 >> testOutput.txt
python3 tweet.py 6 17 >> testOutput.txt
python3 tweet.py 6 18 >> testOutput.txt
python3 tweet.py 6 19 >> testOutput.txt
python3 tweet.py 6 20 >> testOutput.txt
python3 tweet.py 6 21 >> testOutput.txt
python3 tweet.py 6 22 >> testOutput.txt
python3 tweet.py 6 23 >> testOutput.txt
python3 tweet.py 6 24 >> testOutput.txt
python3 tweet.py 6 25 >> testOutput.txt
python3 tweet.py 6 26 >> testOutput.txt
python3 tweet.py 6 27 >> testOutput.txt
python3 tweet.py 6 28 >> testOutput.txt
python3 tweet.py 6 29 >> testOutput.txt
python3 tweet.py 6 30 >> testOutput.txt
python3 tweet.py 7 1 >> testOutput.txt
python3 tweet.py 7 2 >> testOutput.txt
python3 tweet.py 7 3 >> testOutput.txt
python3 tweet.py 7 4 >> testOutput.txt
python3 tweet.py 7 5 >> testOutput.txt
python3 tweet.py 7 6 >> testOutput.txt
python3 tweet.py 7 7 >> testOutput.txt
python3 tweet.py 7 8 >> testOutput.txt
python3 tweet.py 7 9 >> testOutput.txt
python3 tweet.py 7 10 >> testOutput.txt
python3 tweet.py 7 11 >> testOutput.txt
python3 tweet.py 7 12 >> testOutput.txt
python3 tweet.py 7 13 >> testOutput.txt
python3 tweet.py 7 14 >> testOutput.txt
python3 tweet.py 7 15 >> testOutput.txt
python3 tweet.py 7 16 >> testOutput.txt
python3 tweet.py 7 17 >> testOutput.txt
python3 tweet.py 7 18 >> testOutput.txt
python3 tweet.py 7 19 >> testOutput.txt
python3 tweet.py 7 20 >> testOutput.txt
python3 tweet.py 7 21 >> testOutput.txt
python3 tweet.py 7 22 >> testOutput.txt
python3 tweet.py 7 23 >> testOutput.txt
python3 tweet.py 7 24 >> testOutput.txt
python3 tweet.py 7 25 >> testOutput.txt
python3 tweet.py 7 26 >> testOutput.txt
python3 tweet.py 7 27 >> testOutput.txt
python3 tweet.py 7 28 >> testOutput.txt
python3 tweet.py 7 29 >> testOutput.txt
python3 tweet.py 7 30 >> testOutput.txt
python3 tweet.py 7 31 >> testOutput.txt
python3 tweet.py 8 1 >> testOutput.txt
python3 tweet.py 8 2 >> testOutput.txt
python3 tweet.py 8 3 >> testOutput.txt
python3 tweet.py 8 4 >> testOutput.txt
python3 tweet.py 8 5 >> testOutput.txt
python3 tweet.py 8 6 >> testOutput.txt
python3 tweet.py 8 7 >> testOutput.txt
python3 tweet.py 8 8 >> testOutput.txt
python3 tweet.py 8 9 >> testOutput.txt
python3 tweet.py 8 10 >> testOutput.txt
python3 tweet.py 8 11 >> testOutput.txt
python3 tweet.py 8 12 >> testOutput.txt
python3 tweet.py 8 13 >> testOutput.txt
python3 tweet.py 8 14 >> testOutput.txt
python3 tweet.py 8 15 >> testOutput.txt
python3 tweet.py 8 16 >> testOutput.txt
python3 tweet.py 8 17 >> testOutput.txt
python3 tweet.py 8 18 >> testOutput.txt
python3 tweet.py 8 19 >> testOutput.txt
python3 tweet.py 8 20 >> testOutput.txt
python3 tweet.py 8 21 >> testOutput.txt
python3 tweet.py 8 22 >> testOutput.txt
python3 tweet.py 8 23 >> testOutput.txt
python3 tweet.py 8 24 >> testOutput.txt
python3 tweet.py 8 25 >> testOutput.txt
python3 tweet.py 8 26 >> testOutput.txt
python3 tweet.py 8 27 >> testOutput.txt
python3 tweet.py 8 28 >> testOutput.txt
python3 tweet.py 8 29 >> testOutput.txt
python3 tweet.py 8 30 >> testOutput.txt
python3 tweet.py 8 31 >> testOutput.txt
python3 tweet.py 9 1 >> testOutput.txt
python3 tweet.py 9 2 >> testOutput.txt
python3 tweet.py 9 3 >> testOutput.txt
python3 tweet.py 9 4 >> testOutput.txt
python3 tweet.py 9 5 >> testOutput.txt
python3 tweet.py 9 6 >> testOutput.txt
python3 tweet.py 9 7 >> testOutput.txt
python3 tweet.py 9 8 >> testOutput.txt
python3 tweet.py 9 9 >> testOutput.txt
python3 tweet.py 9 10 >> testOutput.txt
python3 tweet.py 9 11 >> testOutput.txt
python3 tweet.py 9 12 >> testOutput.txt
python3 tweet.py 9 13 >> testOutput.txt
python3 tweet.py 9 14 >> testOutput.txt
python3 tweet.py 9 15 >> testOutput.txt
python3 tweet.py 9 16 >> testOutput.txt
python3 tweet.py 9 17 >> testOutput.txt
python3 tweet.py 9 18 >> testOutput.txt
python3 tweet.py 9 19 >> testOutput.txt
python3 tweet.py 9 20 >> testOutput.txt
python3 tweet.py 9 21 >> testOutput.txt
python3 tweet.py 9 22 >> testOutput.txt
python3 tweet.py 9 23 >> testOutput.txt
python3 tweet.py 9 24 >> testOutput.txt
python3 tweet.py 9 25 >> testOutput.txt
python3 tweet.py 9 26 >> testOutput.txt
python3 tweet.py 9 27 >> testOutput.txt
python3 tweet.py 9 28 >> testOutput.txt
python3 tweet.py 9 29 >> testOutput.txt
python3 tweet.py 9 30 >> testOutput.txt
python3 tweet.py 10 1 >> testOutput.txt
python3 tweet.py 10 2 >> testOutput.txt
python3 tweet.py 10 3 >> testOutput.txt
python3 tweet.py 10 4 >> testOutput.txt
python3 tweet.py 10 5 >> testOutput.txt
python3 tweet.py 10 6 >> testOutput.txt
python3 tweet.py 10 7 >> testOutput.txt
python3 tweet.py 10 8 >> testOutput.txt
python3 tweet.py 10 9 >> testOutput.txt
python3 tweet.py 10 10 >> testOutput.txt
python3 tweet.py 10 11 >> testOutput.txt
python3 tweet.py 10 12 >> testOutput.txt
python3 tweet.py 10 13 >> testOutput.txt
python3 tweet.py 10 14 >> testOutput.txt
python3 tweet.py 10 15 >> testOutput.txt
python3 tweet.py 10 16 >> testOutput.txt
python3 tweet.py 10 17 >> testOutput.txt
python3 tweet.py 10 18 >> testOutput.txt
python3 tweet.py 10 19 >> testOutput.txt
python3 tweet.py 10 20 >> testOutput.txt
python3 tweet.py 10 21 >> testOutput.txt
python3 tweet.py 10 22 >> testOutput.txt
python3 tweet.py 10 23 >> testOutput.txt
python3 tweet.py 10 24 >> testOutput.txt
python3 tweet.py 10 25 >> testOutput.txt
python3 tweet.py 10 26 >> testOutput.txt
python3 tweet.py 10 27 >> testOutput.txt
python3 tweet.py 10 28 >> testOutput.txt
python3 tweet.py 10 29 >> testOutput.txt
python3 tweet.py 10 30 >> testOutput.txt
python3 tweet.py 10 31 >> testOutput.txt
python3 tweet.py 11 1 >> testOutput.txt
python3 tweet.py 11 2 >> testOutput.txt
python3 tweet.py 11 3 >> testOutput.txt
python3 tweet.py 11 4 >> testOutput.txt
python3 tweet.py 11 5 >> testOutput.txt
python3 tweet.py 11 6 >> testOutput.txt
python3 tweet.py 11 7 >> testOutput.txt
python3 tweet.py 11 8 >> testOutput.txt
python3 tweet.py 11 9 >> testOutput.txt
python3 tweet.py 11 10 >> testOutput.txt
python3 tweet.py 11 11 >> testOutput.txt
python3 tweet.py 11 12 >> testOutput.txt
python3 tweet.py 11 13 >> testOutput.txt
python3 tweet.py 11 14 >> testOutput.txt
python3 tweet.py 11 15 >> testOutput.txt
python3 tweet.py 11 16 >> testOutput.txt
python3 tweet.py 11 17 >> testOutput.txt
python3 tweet.py 11 18 >> testOutput.txt
python3 tweet.py 11 19 >> testOutput.txt
python3 tweet.py 11 20 >> testOutput.txt
python3 tweet.py 11 21 >> testOutput.txt
python3 tweet.py 11 22 >> testOutput.txt
python3 tweet.py 11 23 >> testOutput.txt
python3 tweet.py 11 24 >> testOutput.txt
python3 tweet.py 11 25 >> testOutput.txt
python3 tweet.py 11 26 >> testOutput.txt
python3 tweet.py 11 27 >> testOutput.txt
python3 tweet.py 11 28 >> testOutput.txt
python3 tweet.py 11 29 >> testOutput.txt
python3 tweet.py 11 30 >> testOutput.txt
python3 tweet.py 12 1 >> testOutput.txt
python3 tweet.py 12 2 >> testOutput.txt
python3 tweet.py 12 3 >> testOutput.txt
python3 tweet.py 12 4 >> testOutput.txt
python3 tweet.py 12 5 >> testOutput.txt
python3 tweet.py 12 6 >> testOutput.txt
python3 tweet.py 12 7 >> testOutput.txt
python3 tweet.py 12 8 >> testOutput.txt
python3 tweet.py 12 9 >> testOutput.txt
python3 tweet.py 12 10 >> testOutput.txt
python3 tweet.py 12 11 >> testOutput.txt
python3 tweet.py 12 12 >> testOutput.txt
python3 tweet.py 12 13 >> testOutput.txt
python3 tweet.py 12 14 >> testOutput.txt
python3 tweet.py 12 15 >> testOutput.txt
python3 tweet.py 12 16 >> testOutput.txt
python3 tweet.py 12 17 >> testOutput.txt
python3 tweet.py 12 18 >> testOutput.txt
python3 tweet.py 12 19 >> testOutput.txt
python3 tweet.py 12 20 >> testOutput.txt
python3 tweet.py 12 21 >> testOutput.txt
python3 tweet.py 12 22 >> testOutput.txt
python3 tweet.py 12 23 >> testOutput.txt
python3 tweet.py 12 24 >> testOutput.txt
python3 tweet.py 12 25 >> testOutput.txt
python3 tweet.py 12 26 >> testOutput.txt
python3 tweet.py 12 27 >> testOutput.txt
python3 tweet.py 12 28 >> testOutput.txt
python3 tweet.py 12 29 >> testOutput.txt
python3 tweet.py 12 30 >> testOutput.txt
python3 tweet.py 12 31 >> testOutput.txt
